server:
  port: 3000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.105.54.147:3306/jc_club?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: gStq9ledLNG9PbeLOdga57vr+Xzx0gkWCKHwRg8PkGXMVKFJj6zD5FOStjZgqClhSpWNA964NHhE00VLtERPsQ==
    type: com.alibaba.druid.pool.DruidDataSource

    ## ================druid===================
    druid:
      initial-size: 20
      min-idle: 20
      max-active: 100
      max-wait: 60000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: 19991209
      filter:
        stat:
          enabled: true
          slow-sql-millis: 2000
          log-slow-sql: true
        wall:
          enabled: true
        config:
          enabled: true
      connection-properties: config.decrypt=true;config.decrypt.key=${publicKey};

  # ========================时间格式===================
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

logging:
  config: classpath:log4j2-spring.xml

publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAInLBI2B+PObnD/MqT6JbT2NsVLbkqATKcFUBQdJuU1pLDB8s+n4QcJQ/qxoD/dTyrWXA3oTL06iDb0DTad5pRcCAwEAAQ==

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan:
        - com.agony.subject.application.controller

#   - group: '用户模块'
#     paths-to-match: '/user/**'
#     packages-to-scan: com.example.controller.user
#
#   - group: '订单模块'
#     paths-to-match: '/order/**'
#     packages-to-scan: com.example.controller.order
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn