server:
  port: 3000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.105.54.147:3306/jc_club?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: 19991209
    type: com.alibaba.druid.pool.DruidDataSource

    ## ================druid===================
    druid:
      initial-size: 20
      min-idle: 20
      max-active: 100
      max-wait: 60000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: 19991209
      filter:
        stat:
          enabled: true
          slow-sql-millis: 2000
          log-slow-sql: true
        wall:
          enabled: true

  # ========================时间格式===================
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8